// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9I9JoeFjnTBYWnbQq9jLMCmkipjlrvI',
    appId: '1:320568572231:web:56985a778099fdfdaab462',
    messagingSenderId: '320568572231',
    projectId: 'weather-app-1fe37',
    authDomain: 'weather-app-1fe37.firebaseapp.com',
    storageBucket: 'weather-app-1fe37.appspot.com',
    measurementId: 'G-5C5FVRWCKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDas2cZxNIAN8Vp6kw2XoqQ2jUy4YXhHEo',
    appId: '1:320568572231:android:515ac1190df43e57aab462',
    messagingSenderId: '320568572231',
    projectId: 'weather-app-1fe37',
    storageBucket: 'weather-app-1fe37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWlPjXUmbIq1u0mQ3-JnadkGd3tFORRgM',
    appId: '1:320568572231:ios:ddb90323ae44c3daaab462',
    messagingSenderId: '320568572231',
    projectId: 'weather-app-1fe37',
    storageBucket: 'weather-app-1fe37.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWlPjXUmbIq1u0mQ3-JnadkGd3tFORRgM',
    appId: '1:320568572231:ios:ddb90323ae44c3daaab462',
    messagingSenderId: '320568572231',
    projectId: 'weather-app-1fe37',
    storageBucket: 'weather-app-1fe37.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9I9JoeFjnTBYWnbQq9jLMCmkipjlrvI',
    appId: '1:320568572231:web:23cfa24d43130782aab462',
    messagingSenderId: '320568572231',
    projectId: 'weather-app-1fe37',
    authDomain: 'weather-app-1fe37.firebaseapp.com',
    storageBucket: 'weather-app-1fe37.appspot.com',
    measurementId: 'G-8S0LYPH4SF',
  );
}
